export  const ActionReducer = {
    SEARCH_DRINK:"SEARCH_DRINK",
    GET_DRINKS:"GET_DRINKS",
    SET_POST:"SET_POST",
    SET_DRINKS:"SET_DRINKS",
    FETCH_POST_REQUEST:"FETCH_POST_REQUEST",
    FETCH_POST_SUCCESS:"FETCH_POST_SUCCESS",
    FETCH_POST_FAILURE:"FETCH_POST_FAILURE",
    FETCH_IMG_REQUEST:"FETCH_IMG_REQUEST",
    FETCH_IMG_SUCCESS:"FETCH_IMG_SUCCESS",
    FETCH_IMG_FAILURE:"FETCH_IMG_FAILURE"
    
}